var friendList =[
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    picture:"https://randomuser.me/api/portraits/men/77.jpg",
    salary: 76800,
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    picture:"https://randomuser.me/api/portraits/women/70.jpg",
    salary: 98700,
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    picture:"https://randomuser.me/api/portraits/men/22.jpg",
    salary: 65700,
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    picture:"https://randomuser.me/api/portraits/women/12.jpg",
    salary: 34600,
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    picture:"https://randomuser.me/api/portraits/men/33.jpg",
    salary: 45600,
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: 33263,
    },
    phone: "(254)954-1289",
    website: "demarco.info",
  },
  {
    id: 6,
    name: "Kayleigh (Kaelyn)",
    username: "Leopoldo_Corkery",
    picture:"https://randomuser.me/api/portraits/women/74.jpg",
    salary: 86500,
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
    },
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    picture:"https://randomuser.me/api/portraits/men/24.jpg",
    salary: 71900,
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
    },
    phone: "210.067.6132",
    website: "elvis.io",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    picture:"https://randomuser.me/api/portraits/women/82.jpg",
    salary: 54300,
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
    },
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    picture:"https://randomuser.me/api/portraits/men/6.jpg",
    salary: 67500,
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
    },
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
  },
  {
    id: 10,
    name: "Clementina Jemima",
    username: "Moriah.Stanton",
    picture:"https://randomuser.me/api/portraits/women/32.jpg",
    salary: 90800,
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
    },
    phone: "024-648-3804",
    website: "ambrose.net",
  },
  {
    id: 11,
    name: "Adan Alvaro",
    picture:"https://randomuser.me/api/portraits/men/32.jpg",
    salary: 45800,
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
  },
  {
    id: 12,
    name: "Allyson Andra",
    username: "Antonette",
    picture:"https://randomuser.me/api/portraits/women/45.jpg",
    salary: 65790,
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
  },
  {
    id: 13,
    name: "Jon (Jax)",
    username: "Samantha",
    picture:"https://randomuser.me/api/portraits/men/0.jpg",
    salary: 102000,
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
  },
  {
    id: 14,
    name: "Barbara Lebsack",
    username: "Karianne",
    picture:"https://randomuser.me/api/portraits/women/55.jpg",
    salary: 76300,
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
  },
  {
    id: 15,
    name: "Yusuf",
    username: "Kamren",
    picture:"https://randomuser.me/api/portraits/men/71.jpg",
    salary: 56700,
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: 33263,
    },
    phone: "(254)954-1289",
    website: "demarco.info",
  },
  {
    id: 16,
    name: "Thea",
    username: "Moriah.Stanton",
    picture:"https://randomuser.me/api/portraits/women/31.jpg",
    salary: 34500,
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
    },
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
  },
  {
    id: 17,
    name: "Jackson Reichert",
    username: "Delphine",
    picture:"https://randomuser.me/api/portraits/men/15.jpg",
    salary: 45600,
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
    },
    phone: "210.067.6132",
    website: "elvis.io",
  },
  {
    id: 18,
    name: "Isabella (Isie)",
    username: "Maxime_Nienow",
    picture:"https://randomuser.me/api/portraits/women/65.jpg",
    salary: 34900,
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
    },
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
  },
  {
    id: 19,
    name: "Zachariah Weissnat",
    username: "Elwyn.Skiles",
    picture:"https://randomuser.me/api/portraits/men/62.jpg",
    salary: 120900,
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
    },
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
  },
  {
    id: 20,
    name: "Beatrice Bridgett",
    username: "Leopoldo_Corkery",
    picture:"https://randomuser.me/api/portraits/women/84.jpg",
    salary: 54600,
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
    },
    phone: "024-648-3804",
    website: "ambrose.net",
  },
]

export default friendList;